# Generated by Django 4.2.5 on 2023-11-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_alter_class_class_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="class_code",
            field=models.CharField(
                default="", editable=False, max_length=6, unique=True
            ),
        ),
    ]
