# Generated by Django 4.2.5 on 2023-10-27 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0022_exerciseattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExerciseAttempt",
        ),
    ]
