# Generated by Django 4.2.5 on 2023-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0023_delete_exerciseattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentscore",
            name="final_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
