# Generated by Django 4.2.5 on 2023-11-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0024_studentscore_final_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentscore",
            name="final_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
